FROM debian:trixie
RUN apt-get update && apt-get install -y \
    build-essential make docker.io git ca-certificates libffi-dev
RUN git clone https://github.com/ashinn/chibi-scheme.git --depth=1
RUN git clone https://codeberg.org/retropikzel/compile-r7rs.git --depth=1 --branch=silence
WORKDIR /chibi-scheme
RUN make
RUN make install
WORKDIR /compile-r7rs
RUN snow-chibi install --always-yes "(foreign c)"
RUN snow-chibi install --always-yes "(srfi 170)"
RUN make build-chibi
RUN make install

