FROM debian:trixie
RUN apt-get update && apt-get install -y \
    build-essential make docker.io git ca-certificates
RUN git clone https://github.com/ashinn/chibi-scheme.git --depth=1
RUN git clone https://codeberg.org/retropikzel/compile-r7rs.git --depth=1 --branch=silence
WORKDIR /chibi-scheme
RUN make
RUN make install
WORKDIR /compile-r7rs
RUN make
RUN make install

