pipeline {
    agent any

    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }

    stages {
        stage('Tests') {
            steps {
                script {
                    def implementations = sh(script: 'docker run retropikzel1/compile-r7rs:chibi sh -c "compile-r7rs --list-r7rs-schemes"', returnStdout: true).split()

                    parallel implementations.collectEntries { SCHEME ->
                        [(SCHEME): {
                            stage("${SCHEME}") {
                                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                    if("${SCHEME}" == "chicken") {
                                        DOCKERIMG="chicken:5"
                                    } else {
                                        DOCKERIMG="${SCHEME}:head"
                                    }
                                    sh "docker build --build-arg IMAGE=${DOCKERIMG} --build-arg SCHEME=${SCHEME} --tag=foreign-c-system-test-${SCHEME} -f Dockerfile.test ."
                                    sh "docker run -v ${WORKSPACE}:/workdir -w /workdir -t foreign-c-system-test-${SCHEME} sh -c \"timeout 120 make SCHEME=${SCHEME} clean all force-install test\""
                                }
                            }
                        }]
                    }
                }
            }
        }
    }
}
