VERSION=1.1.2
build:
	snow-chibi package \
		--version=${VERSION} \
		--authors="Retropikzel" \
		--doc=README.html \
		--description="Library for running shell commands" \
	retropikzel/system.sld

package-name:
	@echo "retropikzel-system-${VERSION}
