(define-c-library libc '("stdio.h") #f '())
(define-c-procedure fopen libc 'fopen 'pointer '(pointer pointer))
(define-c-procedure fclose libc 'fclose 'int '(pointer))
(define-c-procedure feof libc 'feof 'int '(pointer))
(define-c-procedure ferror libc 'ferror 'int '(pointer))
(define-c-procedure fgetc libc 'fgetc 'int '(pointer))
(define-c-procedure fgets libc 'fgets 'pointer '(pointer int pointer))
(define-c-procedure fputc libc 'fputc 'int '(int pointer))
(define-c-procedure fputs libc 'fputs 'int '(pointer pointer))
(define-c-procedure fread libc 'fread 'int '(pointer int int pointer))
(define-c-procedure fseek libc 'fseek 'int '(pointer long int))
(define-c-procedure ftell libc 'ftell 'long '(pointer))
(define-c-procedure fwrite libc 'fwrite 'int '(pointer int int pointer))
(define-c-procedure getc libc 'getc 'int '(pointer))
(define-c-procedure getchar libc 'getchar 'int '())
(define-c-procedure putc libc 'putc 'int '(int pointer))
(define-c-procedure putchar libc 'putchar 'int '(int))
(define-c-procedure puts libc 'puts 'int '(pointer))
(define-c-procedure remove libc 'remove 'int '(pointer))
(define-c-procedure rename libc 'rename 'int '(pointer pointer))
(define-c-procedure rewind libc 'rewind 'void '(pointer))

