(define-c-library libc '("stdio.h") #f '())
(define-c-procedure fopen libc 'fopen 'pointer '(pointer pointer))
(define-c-procedure fclose libc 'fclose 'int '(pointer))
(define-c-procedure feof 'feof 'int '(pointer))
(define-c-procedure ferror 'ferror 'int '(pointer))
(define-c-procedure fgetc 'fgetc 'int '(pointer))
(define-c-procedure fgetcs 'fgetcs 'pointer '(pointer int pointer))
(define-c-procedure fputc 'fputc 'int '(int pointer))
(define-c-procedure fputs 'fputs 'int '(pointer pointer))
(define-c-procedure fread 'fread 'int '(pointer int int pointer))
(define-c-procedure fseek 'fseek 'int '(pointer long int))
(define-c-procedure ftell 'ftell 'long '(pointer))
(define-c-procedure fwrite 'fwrite 'int '(pointer int int pointer))
(define-c-procedure getc 'fwrite 'int '(pointer))
(define-c-procedure getchar 'getchar 'int '())
(define-c-procedure putc 'putc 'int '(int pointer))
(define-c-procedure putchar 'putchar 'int '(int))
(define-c-procedure puts 'puts 'int '(pointer))
(define-c-procedure remove 'remove 'int '(pointer))
(define-c-procedure rename 'rename 'int '(pointer pointer))
(define-c-procedure rewind 'rewind 'int '(pointer))

